### ISSUE TITLE
Posframe Mac OS black Fullscreen

### ISSUE THREAD

**Issue by abbaswasim** [tumashu/posframe#30]
When I run emacs in Mac OS style fullscreen app, occupying the whole screen I see a second black screen. My steps to reproduce.

Run emacs with a temp home dir;
`HOME=/tmp/tmp-home emacs tmp.el`

`M-x package-install RET posframe RET` 

contents of tmp.el 
```
(require 'posframe)
(defvar my-posframe-buffer " *my-posframe-buffer*")

(with-current-buffer (get-buffer-create my-posframe-buffer)
  (erase-buffer)
  (insert "Hello world"))

(when (posframe-workable-p)
  (posframe-show my-posframe-buffer
                 :position (point)))
```

`M-x eval-buffer`

Whenever this is evaluated the first time a new 'posframe' black fullscreen window appears with a flicker and becomes window in focus. I have to do Alt-Tab to go back to emacs and sometimes that doesn't work either and I am stuck at the black window.

<img width="1680" alt="emacs-after-eval-buffer" src="https://user-images.githubusercontent.com/5260991/58368538-80cce400-7ee6-11e9-8a6b-e9752fee3147.png">

<img width="532" alt="fullscreen-apps" src="https://user-images.githubusercontent.com/5260991/58368543-8b877900-7ee6-11e9-95a3-586fd1379654.png">

In this image you can see I have two fullscreen apps, the actual Emacs app and the `*Minibuf-1*`.

This doesn't happen if emacs is not fullscreen though. Not sure if this is a bug in `posframe` or Emacs child-window?

**Comment by conao3** [comment]
Same here.

However, I have given up on dealing with this issue. It's probably a chilled frame problem.
Use maximize instead of full screen. (use `(toggle-frame-maximized)` instead of `(toggle-frame-fullscreen)` )

**Comment by abbaswasim** [comment]
Ah right. I figured it must be child frame issue but couldn't find any bugs reported there. I do see the flicker issue mentioned https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30699 but that was different. Is it worth submitting an emacs bug?

**Comment by conao3** [comment]
I don't have an opinion on it is worth submitting an emacs bug. Not a few Mac users are in trouble, but I'm not sure if this is Emacs Limitation or MacOS Limitation.

**Comment by conao3** [comment]
Because this package is registered in the ELPA repository, we consider this package to be a common framework for dealing with Child-frame.
For that reason, I think the maintainer of Emacs itself will support it, but I would like to ask @tumashu  for his opinion first.

**Comment by tumashu** [comment]
I have no opinion, for i do not know the status of emacs in macos, i have no mac for test

**Comment by gcv** [comment]
I had this problem with macOS Emacs built using the `ns` (official GNU NextStep) port. It does not happen to me with the `mac` port (https://bitbucket.org/mituharu/emacs-mac/).

@abbaswasim: Which macOS Emacs do you use?

**Comment by conao3** [comment]
I have emacs-26.2 `ns` ver, and emacs-26.1 `mac-port` ver. The issue doesn't occur on `mac-port` ver.
BTW, posframe border in emacs-26.2 `ns` ver is not shown...
![Capture 2019-05-14 21 54 34](https://user-images.githubusercontent.com/4703128/58371904-f53c6d00-7f50-11e9-926f-e85310bb3a6f.png)

**Comment by wasimabbas-arm** [comment]
@gcv I use the one from https://emacsformacosx.com I will give the one from `mac-port` a try.

**Comment by wasimabbas-arm** [comment]
@conao3 yes I could never see border either in my version.

**Comment by abbaswasim** [comment]
I have now moved to `mac-port`. I see improvements already `pos-tip` finally has a themed face. Now `posframe` flickers. I still don't know if this issue is in `posframe` of emacs child frames. If anyone knows better let me know I am happy to submit a bug report otherwise I will close the issue.

**Comment by tumashu** [comment]
flick? suggest a screenshot

**Comment by abbaswasim** [comment]
No more flickers with `posframe` in `mac-port`. Sorry there were typos in my previous comment. I have now corrected it.

**Comment by conao3** [comment]
@tumashu, please rename this issue to `childframe macOS limitation; (black fullscreen, missing border)` or something like this.

**Comment by mpereira** [comment]
I also see this. Emacs 26.3 from EmacsForOSX, macOS 10.14.6, posframe 20200205.928.

Another thing I noticed: sometimes moving down lines in org mode files will get super slow. When using `profiler-start`, I can see that most of the CPU time is going into ivy (I'm using ivy-posframe as well) trying to read from the minibuffer, even though I'm just moving down lines.

It looks like the "background" frames are still registering keys.
```
- command-execute                                                 281  51%
 - call-interactively                                             281  51%
  - funcall-interactively                                         281  51%
   - counsel-M-x                                                  249  45%
    - ivy-read                                                    218  39%
     - apply                                                      218  39%
      - #<compiled 0x44a8cb7d>                                    218  39%
       - apply                                                    218  39%
        - ivy-posframe--read                                      218  39%
         - apply                                                  218  39%
          - #<compiled 0x4419642d>                                218  39%
           - read-from-minibuffer                                 126  22%
            + ivy--queue-exhibit                                   73  13%
            - redisplay_internal (C function)                       1   0%
```

**Comment by trepca** [comment]
Thanks @mpereira, I have the same problem.

**Comment by mpereira** [comment]
> @conao3: However, I have given up on dealing with this issue. It's probably a chilled frame problem.
Use maximize instead of full screen. (use (toggle-frame-maximized) instead of (toggle-frame-fullscreen) )

I tried this:
https://github.com/mpereira/.emacs.d/commit/584219ef72b66f98e8c53f2bc9c26ec19b0d14f6

But still see the same symptoms as reported above.

**Comment by Yanhao** [comment]
experiencing same problem

**Comment by muffinmad** [comment]
I believe child frames must work fine in fullscreen with [this commit](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=bbc48b263485c26c6823eabdbbd7e9af62178e34)

**Comment by Eason0210** [comment]
I have the same issue at Mac os

**Comment by kaiwk** [comment]
This issue exists not only in child frame,  but also in normal frame. I have the same problem when customize helm to display in a separate frame. it seems `internal-border` face attribute `:background` doesn't work with emacs(ns), and emacs(mac) works fine.

I tested the code below on emacs(ns), emacs(mac) and emacs on linux(gtk), turns out both emacs(mac) and emacs on linux works fine, but emacs(ns) does not. 

So, i think it's a bug of emacs(ns).

```elisp
;; from https://lists.gnu.org/r/emacs-devel/2019-03/msg00282.html
(defface test
  '((t (:inherit default :background "green")))
  "Face used by the ivy-posframe."
  :group 'ivy-posframe)

(set-face-background
 'internal-border
 (face-attribute 'test :background)
 (make-frame `((internal-border-width . 100)
               (parent-frame . ,(window-frame)))))

(set-face-background
 'internal-border
 (face-attribute 'test :background)
 (make-frame `((internal-border-width . 100))))
```

**Comment by kaiwk** [comment]
This issue exists not only in child frame,  but also in normal frame. I have the same problem when customize helm to display in a separate frame. it seems `internal-border` face attribute `:background` doesn't work with emacs(ns), where emacs(mac) is fine.

I tested the code below on emacs(ns), emacs(mac) and emacs on linux(gtk), turns out both emacs(mac) and emacs on linux works fine, but emacs(ns) does not. 

So, i think it's a bug of emacs(ns).

```elisp
;; from https://lists.gnu.org/r/emacs-devel/2019-03/msg00282.html
(defface test
  '((t (:inherit default :background "green")))
  "Face used by the ivy-posframe."
  :group 'ivy-posframe)

(set-face-background
 'internal-border
 (face-attribute 'test :background)
 (make-frame `((internal-border-width . 100)
               (parent-frame . ,(window-frame)))))

(set-face-background
 'internal-border
 (face-attribute 'test :background)
 (make-frame `((internal-border-width . 100))))
```

**Comment by mpereira** [comment]
For the record, I fixed the "black fullscreen" issues by using [daviderestivo/homebrew-emacs-head](https://github.com/daviderestivo/homebrew-emacs-head). The "black fullscreen" issue is still reproducible for me in the alternative, [d12frosted/homebrew-emacs-plus](https://github.com/d12frosted/homebrew-emacs-plus).

I'm still unable to get posframe borders working though.

macOS 10.15.5
Emacs 28.0.50 (from https://github.com/daviderestivo/homebrew-emacs-head)
ivy-posframe:
```
Package-Version: 20200528.553
Package-Commit: 44749562a9e68bd43ccaa225b31311476fab1251
```

**Comment by muffinmad** [comment]
@mpereira See [this commit](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=c4c5db3de70b55f8bc03c9fee35e29d60f41f16e). Try to reinstall Emacs and see if internal borders is working.

**Comment by agzam** [comment]
@muffinmad yay! finally!

**Comment by mpereira** [comment]
I recompiled Emacs and I get posframe borders now! Thanks for the ping, @muffinmad!

**Comment by mpereira** [comment]
Folks using Linux, are you able to create frames with both an external/outer border and an internal border? I tried to set both in posframe (with some code changes in `posframe.el`) but was unable to do so on macOS.

My intention was to use the internal border as padding between the frame content and the actual border. 

https://www.gnu.org/software/emacs/manual/html_node/elisp/Frame-Layout.html
![image](https://user-images.githubusercontent.com/112426/94992588-5768a180-058b-11eb-8b31-cc000b02a07c.png)

**Comment by muffinmad** [comment]
@mpereira I suggest you to ask this question on the emacs-devel mailing list or fill the bugreport via `M-x report-emacs-bug`.

**Comment by wd** [comment]
I have installed `emacs-head@28` from `daviderestivo/homebrew-emacs-head`, fixed the black screen, but still no border. I have tried `emacs-mac`, it has border, but the popup menu flicker when I move the cursor up and down.

**Comment by tarlig** [comment]
I migrated to emacs-mac from emacs-plus to get this fixed, but I still have problems. In emacs-mac I see the border around the child frame, but after some time of usage it disappers and reappers only in new frames.

This problem has been reported also here: https://github.com/emacs-lsp/lsp-ui/issues/21

**Comment by tarlig** [comment]
> (load-theme 'xx t)

I can confirm that changing or reloading theme fixes this problem. So that works as a temporary solution.

**Comment by tarlig** [comment]
> I have installed `emacs-head@28` from `daviderestivo/homebrew-emacs-head`, it fixed the black screen and the border issue.

I just brew installed `emacs-head@28` as well, but problem of disappearing child frame border still occurs. I can always fix it by changing a theme, until frame disappers some minutes later again.

**Comment by wd** [comment]
> I just brew installed `emacs-head@28` as well, but problem of disappearing child frame border still occurs. I can always fix it by changing a theme, until frame disappers some minutes later again.

It's probably related with your config, maybe you can try to remove most of the configs and test again? Like I have issues with the `ns-system-appearance-change-functions`, maybe there are some similar things happened to you.

**Comment by tarlig** [comment]
Might be the case indeed, but I have a `init.el` file with 2k lines, and a `custom.el` file with a few hundred lines of code. Debugging and pinpointing the error will take some time. - But thanks for the hint.

Btw: `emacs-head@28` from `daviderestivo/homebrew-emacs-head` is super fast on my Mac (opening new frames: in an instant). Thank you for the suggestion.
